version: '3.8'

services:
  # Node.js Application
  pafin_app:
    container_name: pafin_app
    build: ./
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      NODE_ENV: development
      DB_HOST: postgres_container
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/app/
    command: sh -c "cd /app/src && npm install && npm run dev"

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
